### ISSUE TITLE
Adjust constraints in JamVC

### ISSUE THREAD

**Issue by shredlocker** [cpmpercussion/microjam#16]
Had a problem with constraints when clicking the cancel button and there are no previous performances in the stack. Maybe there are a better way of setting up the constraints so that it is easier to add and remove ChirpView programmatically.

**Comment by shredlocker** [comment]
Used the ChirpView in storyboard as a reference view. No performances are loaded in to that view, only used for constraints for now.

**Comment by cpmpercussion** [comment]
Ok - this seems like a good idea, but it's still not quite working on small devices. E.g., on iPhone SE, the views are laid out correctly in the storyboard, but not in the app. If you press cancel in the Jam tab, you end up in an inconsistent state, but the views go back to being laid out correctly.

**Comment by cpmpercussion** [comment]
I think this has now been resolved in #40 and others
