### ISSUE TITLE
Storing "jamversations" on the cloud

### ISSUE THREAD

**Issue by shredlocker** [cpmpercussion/microjam#17]
Store every unique performance and add a jamversation field in the db with a list of pointers to all the performances in the jamversation.

**Comment by cpmpercussion** [comment]
Why not just have a pointer to the immediate parent performance (as presently implemented)? In other words, jamversations are stored as trees.

I imagine that when there are threads of quite a lot of jams, there could be performance issues loading the whole thread, particularly if some jams distantly related jams are not stored locally and must be fetched from the store. I think in this case, it would be fine just to truncate the jamversation at some limited point - especially until we see how these things might sound and how the interaction feels.

**Comment by cpmpercussion** [comment]
This is really an old version of #53 which is currently in progress.
