### ISSUE TITLE
Separate navigation buttons and performance buttons

### ISSUE THREAD

**Issue by shredlocker** [cpmpercussion/microjam#19]
Use the cancel button to cancel the whole performance, add a button for resetting the performance or reply. Think that is more intuitive for the users.

**Comment by cpmpercussion** [comment]
fair call - I think a context-sensitive button would be appropriate - there's probably too many buttons on the jam screens as it stands, but, for instance, it doesn't make sense to have a reply button if you're already in an unrecorded reply.

**Comment by shredlocker** [comment]
Yep, thought about just replacing the "reply" with "reset" for now.

**Comment by cpmpercussion** [comment]
Thinking a bit further - I think that ultimately, the three button and labels under the chirp view have to go. they're quite ugly and cause problems with layout.

I wonder if the navigation bar buttons can be better utilised or make it more clear about what state the app is in..

good to experiment with this, but maybe better to do so in a different feature branch.

**Comment by cpmpercussion** [comment]
the buttons have ended up a bit confused again - reply seems to get greyed out too much. This is still an issue to think about.

**Comment by cpmpercussion** [comment]
This is closed now with the new transport and record enable controls
