### ISSUE TITLE
No testing

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#20]
MicroJam has no testing. It would be fun to have a few UI tests for the reply mechanism especially.

**Comment by shredlocker** [comment]
Jup, good idea! I don't have much experience with testing, but that's something I should learn how to do! What kind of tests did you have in mind?

**Comment by cpmpercussion** [comment]
Here's a decent [getting started guide](https://medium.com/@johnsundell/getting-started-with-xcode-ui-testing-in-swift-ac7b1f5101e5).

UI testing is a fun party trick! (app opens and remote controls for a while).

I would suggest just using basic Swift UITesting procedure for now (as outlined in above article), but there are [frameworks to help with more advanced procedures](https://www.appcoda.com/automated-ui-test/).

whoever gets there first: make a branch with a basic UI test and then we can decide how to proceed.

**Comment by cpmpercussion** [comment]
fixed in 8d318ec

Best to focus on UITests in this project: integration with the different components and web features is most important to users.

Unit Tests are blocked a bit by cocoa pods - they _should_ work, but don't and the time needed to fix this is probably not worth it right now.
