### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by shredlocker** [cpmpercussion/microjam#23]
Before we start implementing UI testing, should we update the UI? As you said, the three buttons have to go. We can make the size classes work as well.

**Comment by cpmpercussion** [comment]
well yes, but I'm not sure about how to update the UI and this might be a longer process. Would certainly be good to have a few UI tests that relate to the table view and the ChirpView - basically making sure that the correct views load and display when going down certain user paths.

happy to tweak things later if the view layout changes, but no reason not to learn about UI testing and implement a few simple ones:

- tap a performance in the list, assert that the performance controller loads and the chirp view is visible
- hit play, assert that timers are produced and progress bar starts moving
- etc

**Comment by shredlocker** [comment]
Yep, I'll start working on that after the merge tomorrow.

**Comment by shredlocker** [comment]
I have played around with the UI design, just because I think it's fun and I'm not that good yet so lots of things to learn! This shows you some of the ideas I've had.
![image](https://user-images.githubusercontent.com/19956175/28369992-74943a78-6c99-11e7-8c24-324d80358b2f.png)

**Comment by cpmpercussion** [comment]
wow that looks nice!

**Comment by cpmpercussion** [comment]
Look at that nice UI! Let's keep pushing towards something a bit cleaner and like this!

**Comment by cpmpercussion** [comment]
The UI has been updated significantly, so I'm closing this issue. I'd like to see @shredlocker's current enhanced version, but it should merge in present changes.
