### ISSUE TITLE
Adding more user features

### ISSUE THREAD

**Issue by shredlocker** [cpmpercussion/microjam#24]
Have you thought about having more user features? User can have jamversations with their friends etc. I know Firebase have great support for connecting apps with Facebook, Google etc.

**Comment by cpmpercussion** [comment]
OOH, how about a screen where you can compose performances by adding different jams together,

maybe you could sort jams by instrument/performer/time and pick ones to layer up.

you might also be able to select particular jams from a jamversation to keep in a performance - there could be a way to publish these compositions separately from the main jam view?

This would not be so hard to do: maybe a collection view to arrange jams differently - good bit of UI coding in that! :-)

**Comment by cpmpercussion** [comment]
Ok I've added a few issues with outstanding features to add - add more ideas to this thread when you have them or just make new issues!

**Comment by cpmpercussion** [comment]
Closing as we're expanding this issue into other more specific ideas
