### ISSUE TITLE
threaded replies

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#25]

**Comment by cpmpercussion** [comment]
looking pretty good in the threaded-replies branch, will merge into dev branch tomorrow - any last commits to go in?

**Comment by shredlocker** [comment]
I think it's ready. I might add some comments.

**Comment by cpmpercussion** [comment]
ok - you can do it in the dev branch! I'm going to confirm the PR I set up.

**Comment by cpmpercussion** [comment]
fixed in #29 thanks for your work on this @shredlocker

**Comment by cpmpercussion** [comment]
I've updated the beta available in TestFlight - tomorrow I'll check this out for GUI bugs or anything and add as issues if I find them
