### ISSUE TITLE
build 31 cancel button does not work when viewing jams in list

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#31]
After opening a jam from the world view and tapping cancel, the button is greyed out but view does not unwind and app is then unresponsive.

**Comment by shredlocker** [comment]
It does seem to work fine in the simulator. I haven't had any issues with this so far.

**Comment by cpmpercussion** [comment]
weird - also could be due to my weird phone which has been behaving badly today. 

I'll see if I can isolate the issue or close sometime soon; maybe I'll write a test to pin it down! :-)

**Comment by cpmpercussion** [comment]
this has been fixed (apparently), tests pass and works in release build
