### ISSUE TITLE
build 31 crashes when scrolling world jam view

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#32]
when scrolling down the world jam view, movement stops and app becomes unresponsive.

**Comment by shredlocker** [comment]
It looks like it crashes when it's loading new jams into the table..

**Comment by cpmpercussion** [comment]
exactly, I've seen this in the TestFlight build and debug build both on device and in sim.

**Comment by cpmpercussion** [comment]
weird part is that it doesn't seem to actually crash! Just becomes unresponsive.

**Comment by cpmpercussion** [comment]
this bug is caused by a while loop in WorldJamsTableViewController going crazy while loading reply images. (highlighted in a7f5c46)

`        while temp.replyto != "" {
            if let replyPerf = appDelegate.fetchPerformanceFrom(title: temp.replyto) {
                cell.context.text = creditString(originalPerformer: replyPerf.performer)
                images.append(replyPerf.image)
                temp = replyPerf
            }
            // FIXME: This goes into an infinite loop under some circumstances.
            print("loaded a reply")
        }`

Not sure why this loop runs forever, but regardless I would suggest limiting the reply image loading to about 5 so that it doesn't slow down the tableview.

**Comment by cpmpercussion** [comment]
fixed in ec7bfe3 lol

**Comment by shredlocker** [comment]
I think the problem is that even though the reply string is not empty, fetchPerformanceFrom(title: ) only search through the stored performances, but the performance we're trying to fetch is not in that array. Maybe add something that will get the performance from the cloud if it's not in the array.
