### ISSUE TITLE
wrong colours for recorded performances

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#33]
performances are always recorded in red and played back in the "microjam colour" setting. They should be recorded in the set colour and played back in a slightly lighter colour.

![simulator screen shot 20 jul 2017 3 07 50 pm](https://user-images.githubusercontent.com/261139/28401440-57c42628-6d5d-11e7-8dc3-1204e812600e.png)
![simulator screen shot 20 jul 2017 3 06 18 pm](https://user-images.githubusercontent.com/261139/28401443-5d7713fa-6d5d-11e7-983b-0751490d12a8.png)

**Comment by shredlocker** [comment]
Fixed

**Comment by cpmpercussion** [comment]
Closed with #0a70b60 thanks @shredlocker !
