### ISSUE TITLE
tapping save in jam tab does not clear the performance view

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#34]
when you tap save, the view segues to the world tab (as it should) but does not clear the jam tab. i.e., if you then return to the jam tab there is no way to record again until tapping cancel.

**Comment by shredlocker** [comment]
I'm gonna fixed that! I can just do that in the dev branch, or should I make a new branch for small things like that?

**Comment by cpmpercussion** [comment]
Yep just do small stuff in the dev branch. Thx!

--Charles
