### ISSUE TITLE
Issues building the develop branch

### ISSUE THREAD

**Issue by shredlocker** [cpmpercussion/microjam#36]
I'm having trouble getting the app to build on the develop branch. Looks like I'm missing files, especially the new test files you added. I don't know if it has something to do with the few lines of code I added just now.. It did say that there was no problem committing the change.

**Comment by shredlocker** [comment]
This is the error message I get.

![image](https://user-images.githubusercontent.com/19956175/28413535-2a17c3ca-6d48-11e7-93eb-3e88b9b04498.png)

**Comment by cpmpercussion** [comment]
Arg I'll have a look in a minute. I changed some stuff for cocoa pods.

One of the test targets doesn't build right now but this shouldn't affect the main target. 

Maybe clean and build?

**Comment by shredlocker** [comment]
I tried cleaning it, but still not building..

**Comment by cpmpercussion** [comment]
Ok sorry about that, added missing pure-data source in #affa4dc

could you pull and try again?

**Comment by cpmpercussion** [comment]
mine builds now but not the unit testing target, I'm working on that a bit this evening.
<img width="248" alt="screenshot 2017-07-20 21 31 16" src="https://user-images.githubusercontent.com/261139/28415396-e0e1296c-6d92-11e7-84cc-f88ef42bf23a.png">

**Comment by shredlocker** [comment]
Yep, that did it!
