### ISSUE TITLE
build 35: crackly audio with lots of replies

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#39]
in build 35 I hear some crackly audio after loading and recording a lot of replies. Could it be that performances are not being closed correctly after use - leaving the pd file open?

**Comment by shredlocker** [comment]
I'm note sure, I'll have a look at that!

**Comment by cpmpercussion** [comment]
I made a small change closing pd files could have been left open in recording views from a sequence of replies, that might have solved this problem . I'm closing for now.
