### ISSUE TITLE
User system

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#42]
microjam needs a very simple user system to store stage names, avatars, and small descriptions in CloudKit. Then users could follow each other etc.

I've started this feature in the [user-system](https://github.com/cpmpercussion/microjam/tree/user-system) branch.

**Comment by cpmpercussion** [comment]
PS, this branch also shows how to do separate storyboards for each viewcontroller which should be the right practice going forward.

**Comment by cpmpercussion** [comment]
Hey Henrik - could you check out the user-system branch today? build it and have a look at the new settings screen (still pretty lame, but you can add an avatar now).

**Comment by shredlocker** [comment]
I'll check it out!

**Comment by shredlocker** [comment]
I'm running into this when running in the simulator..

![image](https://user-images.githubusercontent.com/19956175/28966026-3717f31a-7914-11e7-86c9-272510a4ed50.png)

**Comment by cpmpercussion** [comment]
Darn it! I'll have to test from a blank slate. sorry!

**Comment by shredlocker** [comment]
it's when I'm trying to edit the avatar image. I'm selecting an image in the camera roll and then I get the error.

**Comment by shredlocker** [comment]
I like that the slider changes color when you move it!

**Comment by cpmpercussion** [comment]
me too!

**Comment by cpmpercussion** [comment]
note my clever (and Swifty) singleton pattern in UserProfile!

**Comment by cpmpercussion** [comment]
if you feel like it, you could debug that error, I might be able to look a bit tomorrow, but getting tired now 😴

**Comment by shredlocker** [comment]
The singleton is a nice touch! I can do some debuging. I see that you do the fetching from the database inside the class, maybe I should do the same with the search/browse thingy..

**Comment by shredlocker** [comment]
All the users should probably have a public profile, or public info as well? Right now I can't query specific users by their stagename etc, I think....

**Comment by cpmpercussion** [comment]
I've addressed that crash - the app now behaves correctly if you're not logged into iCloud. 

It's not quite reloading the views proactively enough, but it doesn't crash now if you happen to be logged out.
