### ISSUE TITLE
Add accessibility labels and hints to all viewcontrollers. 

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#45]
Vision impaired users could easily use microjam, very easy to implement accessibility features.

**Comment by cpmpercussion** [comment]
This kind of thing would be good for the second RC.

**Comment by benediktewallace** [comment]
Accessibility warnings in most views refer to "hit area is too small" or "Dynamic text font sizes are unsupported". Not sure if this is something you are concerned about (add new issue?) or if it should be ignored.

**Comment by cpmpercussion** [comment]
Good idea to add it as an issue, as it could be useful to investigate later, but not a priority for now. I’m not sure about what accessibility warnings tell us! Any other things that need to be sorted out!

**Comment by cpmpercussion** [comment]
How did this go? Is it done? can we close?

**Comment by benediktewallace** [comment]
Yup, all elements should be covered now, though new ones have kept popping up during testing. I think this issue can be closed.

Does this issue overlap with #107  ?
