### ISSUE TITLE
Performance Store delegate

### ISSUE THREAD

**Issue by shredlocker** [cpmpercussion/microjam#48]
Do you have any ideas how to do the delegating with the performance store? I don't really know what would be the best solution here. I need to have the performances that I fetch from the cloud sent back to the object that requested the query.

**Comment by cpmpercussion** [comment]
I think the simplest way would be to make a function in the performanceStore like:

`func fetchPerformanceByReferenceFor(chirpView view: ChirpView)`

which updates the view with the fetched performance in the completion block.

So in the ViewController, you would create the dummy ChirpViews to be filled in with performances once the request comes back.

Alternatively, you could do something fancy with NSNotifications?

**Comment by shredlocker** [comment]
I misunderstood what the performanceStore actually is! I was thinking of a database handler. Maybe implement that kind of an object so it's easy to get the stuff we need from the database, not only performances, but searching for usernames etc...

**Comment by cpmpercussion** [comment]
I dunno about a more general classs... there's only two types in the database: Users, and Performances. And isn't cloud kit sort of a database handler already?

Maybe you could make an extension for ChirpView with a special initialiser that looks up it's own performance?

Hrm - I'll keep thinking, happy to look at any ideas you come up with to handle needed function elegantly!

**Comment by shredlocker** [comment]
Forget about a separate class.. makes it just more difficult!

**Comment by cpmpercussion** [comment]
Yep fine, I think that as we go along, more classes will reference CloudKit and do some queries which is fine.
