### ISSUE TITLE
Playing performances outside of the chirpView class

### ISSUE THREAD

**Issue by shredlocker** [cpmpercussion/microjam#54]
When browsing for performances or searching for performances, I think it is a good idea to be able to preview the performance before adding it to the ChirpJam. Playing performances outside of the chirpview is not straight forward right now. Any ideas?

I've made it work, but I'm creating a chirpView without actually using it besides playing the performance...

**Comment by cpmpercussion** [comment]
Do you mean playing the sound and animation together? My idea for the ChirpView class was that it should _mainly_ be about playback. So I think it's fine to make ChirpViews just to playback performances.

**Comment by cpmpercussion** [comment]
Any more thoughts about this? I guess removing the ChirpView recording functions helped clarify the use of that class.

**Comment by shredlocker** [comment]
This is not a problem anymore since we are always using the chirp view when we are playing back performance from now on.
