### ISSUE TITLE
When saving a jam, the jam is not displayed in the feed. 

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#61]
After recording a jam and pressing save, the feed should scroll up to show that very jam displayed. 

This is especially a problem with composed jams: they're not really saved at all as far as I can tell?

**Comment by shredlocker** [comment]
This works for now.. might still need some more work later, but that is mostly because of the createBy attribute. Fixed in 82e0c361b3f9a9e56d63c17b8373267333f2e39e
