### ISSUE TITLE
reply button not working right now?

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#64]
in the dev branch the reply button is always greyed out.
![screenshot 2017-08-15 11 54 05](https://user-images.githubusercontent.com/261139/29311030-74728794-81b0-11e7-8620-8d8eabd4c1d7.png)

**Comment by shredlocker** [comment]
Will fix!

**Comment by shredlocker** [comment]
Fix in aab333ea40a19046564c808c19a6ae57d9f3c0c4
