### ISSUE TITLE
changing interactivity on recording view

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#65]
in the ChirpJamViewController, the recording view is also used to store _just recorded_ performances, and interactivity is turned off. I think it would be better to move the just recorded performance to the stack of playback views (but keep track of it), and keep interactivity on so that users can doodle around without recording the whole thing.

Thoughts?

**Comment by cpmpercussion** [comment]
Hm, now it seems like the recording stops, interactivity stays on, but you can swipe, just tap? weird.

**Comment by shredlocker** [comment]
It would be nice to be able to get the feel of the instrument before recording. Would need some kind of recording enabled button? I guess we could use the reply button for that, we don't need to doodle around if we only have loaded a performance..

**Comment by shredlocker** [comment]
I added a cool tail effect when the user is interacting with the chirp view without recording being enabled. I consider this fixed in 2a6b9a889dc864dd818552460f902da391d005d5
