### ISSUE TITLE
background colour not used

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#66]
Background colour needs to be stored in performances and displayed on the screen.

- if recording a new jam, the present users bg colour should be used.
- if playing back / replying, the root nodes bg colour should be used.

this should also apply to the feed.

**Comment by cpmpercussion** [comment]
background colour is now being saved and stored in performances (as of 9a2d9cf) but is not used in the UI. @shredlocker could you have a look at that?

**Comment by shredlocker** [comment]
Yes! So the background color should be set to the background color of the performance?

**Comment by cpmpercussion** [comment]
Yep, I guess set the background colour of the container view and use the colour of the top most performance in the stack, or of the user's preference if recording

**Comment by shredlocker** [comment]
Background color is now in use with b5cd34e164734dcf83e6c1eafc8bc13b474c83d9

**Comment by cpmpercussion** [comment]
Cool! That looks a bit nicer now, but I might tune it so that it's a bit more... aesthetically acceptable! :-)
