### ISSUE TITLE
dev not loading replies

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#69]
right now replies are not loaded when playing back jams e.g.,

![screenshot 2017-08-16 10 58 20](https://user-images.githubusercontent.com/261139/29355615-0e6e7742-8272-11e7-84bd-0405c098aee5.png)
![screenshot 2017-08-16 10 58 28](https://user-images.githubusercontent.com/261139/29355616-0ee15abe-8272-11e7-88e7-c4fee22409b1.png)

**Comment by shredlocker** [comment]
That's a quick fix!

**Comment by shredlocker** [comment]
Fixed in f1f0083953cf9e327b8fd015986037c7a9e387a6
Don't know why the PerformanceController suddenly appeared in the develop branch... everything still works!
